version: '2'
services:
  drupal:
    user: "1000000"
    hostname: drupal
    build: .
    image: drupal8
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    user: "1000000"
    hostname: mysql
    image: 1and1internet/ubuntu-16-nginx-php-phpmyadmin-mariadb-10 
    ports:
      - "8081:8080"
#      - "3306:3306"
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: EnvVarHere 
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: 82LqaSc2V5BT5eyx
