apiVersion: v1
kind: Template
labels:
    template: apache-php5.6-mysql-drupal-template
metadata:
  name: drupal8-php5.6-apache-ephemeral
  annotations:
    description: "Drupal 8 on Apache 2.4 and PHP 5.6"
    iconClass: "icon-php"
    tags: "quickstart,php,drupal"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Apache 2.4
    name: ${APP_SERVICE_NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_SERVICE_NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for deploying Apache
    labels:
      service: apache-2.4
    name: ${APP_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${APP_SERVICE_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${APP_SERVICE_NAME}
          service: apache-2.4
        name: ${APP_SERVICE_NAME}
      spec:
        containers:
        - env:
          image: 1and1internet/ubuntu-16-apache-2.4-php-5.6-drupal-8:unstable
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
                port: 8080
            timeoutSeconds: 1
          name: ${APP_SERVICE_NAME}
          volumeMounts:
          - mountPath: /var/www/html
            name: apache-data
        restartPolicy: Always
        securityContext:
          runAsUser: 1000580030
        volumes:
        - emptyDir:
            medium: ""
          name: apache-data
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: MySQL and phpMyAdmin
    creationTimestamp: null
    name: ${DATABASE_SERVICE_NAME}
  spec:
    portalIP: ""
    ports:
    - name: mysql
      nodePort: 0
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
    selector:
      name: ${DATABASE_APP_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${DATABASE_SERVICE_NAME}
  spec:
    to:
      kind: Service
      name: ${DATABASE_SERVICE_NAME}
    port:
      targetPort: 8080
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for deploying MySQL
    labels:
      service: mysql-5.7
    name: ${DATABASE_APP_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_APP_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_APP_SERVICE_NAME}
          service: mysql-5.7
        name: ${DATABASE_APP_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_ROOT_PASSWORD
            value: ${MYSQL_ROOT_PASSWORD}
          image: 1and1internet/ubuntu-16-nginx-1.10.0-php-7.0-phpmyadmin-4.6-mysql-5.7:unstable
          imagePullPolicy: Always
          name: ${APP_SERVICE_NAME}
        securityContext:
          runAsUser: 1000580040
    triggers:
    - type: ConfigChange
parameters:
- description: Size of Storage
  displayName: Web directory size
  name: VOLUME_CAPACITY
  required: true
  value: 5Gi
- description: Application service name
  displayName: Application service name
  name: APP_SERVICE_NAME
  required: true
  from: drupal-[a-z]{5}
  generate: expression
- description: The exposed hostname that will route to the Apache Server, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- description: Size of Database Storage
  displayName: DB directory size
  name: DATABASE_VOLUME_CAPACITY
  required: true
  value: 5Gi
- description: Database application service name
  displayName: Database application service name
  from: mysql-[0-9]{5}
  generate: expression
  name: DATABASE_APP_SERVICE_NAME
  required: true
- description: MySQL Username
  displayName: Username for MySQL
  from: user[A-Z0-9]{4}
  generate: expression
  name: MYSQL_USER
  required: true
- description: MySQL Password
  displayName: Password for MySQL
  from: '[a-zA-Z0-9]{6}'
  generate: expression
  name: MYSQL_PASSWORD
  required: true
- description: MySQL Root Password
  displayName: Password for MySQL Root User
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: MYSQL_ROOT_PASSWORD
  required: true
- description: Service Name for MySQL
  displayName: Service Name for MySQL
  name: DATABASE_SERVICE_NAME
  required: true
  value: mysql
- description: Maximum amount of memory the database container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 512Mi
